version: "3.4"
services:

  wrenidm:
    image: wrensecurity/wrenidm:6.0.1
    container_name: wrenidm
    depends_on:
      - openldap
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./sample_data/conf/provisioner.openicf-ldap.json:/opt/wrenidm/conf/provisioner.openicf-ldap.json
      - ./sample_data/conf/sync.json:/opt/wrenidm/conf/sync.json

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    command: --loglevel debug
    ports:
      - "389:389"
      - "636:636"

    environment:
      LDAP_ORGANISATION: "Wren Security"
      LDAP_DOMAIN: "wrensecurity.org"

