version: "3.8"

services:
  wrenidm:
    image: wrensecurity/wrenidm:6.1.1
    container_name: wrenidm
    depends_on:
      - ldap
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./conf/provisioner.openicf-ldap.json:/opt/wrenidm/conf/provisioner.openicf-ldap.json
      - ./conf/provisioner.openicf-csv.json:/opt/wrenidm/conf/provisioner.openicf-csv.json
      - ./conf/config.properties:/opt/wrenidm/conf/config.properties
      - ./conf/system.properties:/opt/wrenidm/conf/system.properties
      - ./conf/sync.json:/opt/wrenidm/conf/sync.json
      - ./data/hr.csv:/tmp/hr.csv
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_ORGANISATION: "Wren Security"
      LDAP_DOMAIN: "wrensecurity.org"
